image: navarroaxel/node-yarn-scss-lint
cache:
  paths:
    - node_modules/

before_script:
  - yarn install

test:
  script:
    - yarn test
  tags:
    - docker

build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - yarn run build
  only:
    - master
  tags:
    - docker
